export const URL = {
  // home
  '/home': { login: true },
  // myt
  '/myt': { login: true },
  '/myt/usage/change': { login: true },
  '/myt/usage/children': { login: true },
  '/myt/usage/datalimit': { login: true },
  '/myt/usage/datashare': { login: true },
  '/myt/usage/tdatashare': { login: true },
  '/myt/usage/tdatashare/info': { login: true },
  '/myt/usage/tdatashare/close': { login: true },
  '/myt/usage/troaming': { login: true },
  '/myt/usage/ting': { login: true },
  '/usage/24hourdiscount': { login: true },
  '/myt/bill/hotbill': { login: true },
  // recharge
  '/recharge/refill': { login: true },
  '/recharge/refill/history': { login: true },
  '/recharge/refill/select': { login: true },
  '/recharge/refill/complete': { login: true },
  '/recharge/refill/error': { login: true },
  '/recharge/refill/gift': { login: true },
  '/recharge/refill/gift-complete': { login: true },
  '/recharge/refill/gift-products': { login: true },
  '/recharge/gift': { login: true },
  '/recharge/gift/process/family': { login: true },
  '/recharge/gift/process/members': { login: true },
  '/recharge/gift/process/request': { login: true },
  '/recharge/gift/history': { login: true },
  '/recharge/cookiz': { login: true },
  '/recharge/limit': { login: true },
  '/recharge/limit/process': { login: true },
  '/recharge/ting': { login: true },
  '/recharge/ting/process': { login: true },
  '/recharge/ting/history': { login: true },
  // payment
  '/payment/realtime': { login: true },
  '/payment/auto': { login: true },
  '/payment/point': { login: true },
  '/payment/history': { login: true },
  // management
  // membership
  // product
  // direct
  // customer
  // auth
  '/auth/line': { login: true },
  '/auth/line/edit': { login: true },
  '/auth/line/register/guide': { login: true },
  '/auth/line/register/corporation': { login: true },
  '/auth/line/register/empty': { login: true },
  '/auth/login/fail': { login: false },
  '/auth/login/dormancy': { login: false },
  '/auth/login/find-id-pwd': { login: false },
  '/auth/logout/complete': { login: true },
  '/auth/logout/expire': { login: true },
  '/auth/member/management': { login: true },
  '/auth/signup/guide': { login: false },
  '/auth/tid/login': { login: false },
  '/auth/tid/account': { login: true },
  '/auth/tid/change/pw': { login: true },
  '/auth/tid/find/id': { login: false },
  '/auth/tid/find/pw': { login: false },
  '/auth/tid/logout': { login: true },
  '/auth/tid/signup-local': { login: false },
  '/auth/tid/signup-foreigner': { login: false },
  '/auth/tid/guide': { login: false },
  '/auth/withdrawal/guide': { login: true },
  '/auth/withdrawal/survey': { login: true },
  '/auth/withdrawal/complete': { login: false }
};
