export const URL = {
  '/home/postcode': { login: false, id: '00', title: '우편번호' },

  // Main
  '/main/menu/settings': { login: false, id: 'ST_01_01', title: '설정' },
  '/main/menu/settings/business-info': { login: false, id: 'ST_01_08', title: '사업자 정보' },
  '/main/menu/settings/privacy': { login: false, id: 'ST_01_07', title: '개인정보처리방침' },
  '/main/menu/settings/certificates': { login: false, id: 'ST_01_06', title: '공인인증센터' },
  '/main/menu/settings/notification': { login: true, id: 'ST_01_05', title: 'T알림 설정' },
  '/main/menu/settings/terms': { login: false, id: 'GU_02', title: '이용약관' },
  '/main/menu/settings/location': { login: true, id: 'ST_01_04', title: '위치정보 이용 동의 설정' },
  '/main/menu/refund': { login: false, id: 'MN_01_04_01_01', title: '미환급금 조회' },

  // MyT
  '/myt/fare': { login: true, id: 'MF1', title: '나의 요금' },
  '/myt/fare/nonpayment': { login: true, id: 'MF_02', title: '미납요금' },
  '/myt-fare/bill/account': { login: true, id: 'MF_01_01', title: '계좌이체 납부' },
  '/myt-fare/bill/card': { login: true, id: 'MF_01_02', title: '체크/신용카드 납부' },
  '/myt-fare/bill/point': { login: true, id: 'MF_01_03', title: 'OK캐쉬백/T포인트 납부' },
  '/myt-fare/bill/sms': { login: true, id: 'MF_01_04', title: '입금전용계좌 신청' },
  '/myt-fare/bill/cashbag': { login: true, id: 'MF_01_05', title: 'OK캐쉬백 요금납부' },
  '/myt-fare/bill/tpoint': { login: true, id: 'MF_01_06', title: 'T포인트 요금납부' },
  '/myt-fare/bill/option': { login: true, id: 'MF_05_01', title: '납부방법' },
  '/myt-fare/billauto': { login: true, id: 'MF_05_01_01', title: '자동납부 신청 및 변경' },
  '/myt-fare/billsmall': { login: true, id: 'MF_06', title: '소액결제' },
  '/myt-fare/billsmall/auto': { login: true, id: 'MF_06_04', title: '소액결제 자동선결제 신청' },
  '/myt-fare/billsmall/auto/info': { login: true, id: 'MF_06_05', title: '소액결제 자동선결제 변경 및 해지 정보' },
  '/myt-fare/billsmall/auto/change': { login: true, id: 'MF_06_05_01', title: '소액결제 자동선결제 변경' },
  '/myt-fare/billcontents': { login: true, id: 'MF_07', title: '콘텐츠이용료' },
  '/myt-fare/billcontents/auto': { login: true, id: 'MF_07_04', title: '콘텐츠이용료 자동선결제 신청' },
  '/myt-fare/billcontents/auto/info': { login: true, id: 'MF_07_05', title: '콘텐츠이용료 자동선결제 변경 및 해지 정보' },
  '/myt-fare/billcontents/auto/change': { login: true, id: 'MF_07_05_01', title: '콘텐츠이용료 자동선결제 변경' },
  '/myt-fare/billsetup': { login: true, id: 'MF_04', title: '요금 안내서 설정' },
  '/myt-fare/billsetup/historyreturn': { login: true, id: 'MF_04_04', title: '요금안내서 반송내역' },
  '/myt-fare/billsetup/reissue': { login: true, id: 'MF_04_01', title: '요금안내서 재발행' },
  '/myt-fare/billsetup/change': { login: true, id: 'MF_04_02', title: '요금안내서 변경' },
  '/myt-fare/bill/hotbill': { login: true, id: 'MF_03', title: '실시간 사용요금' },

  '/myt/join': { login: true, id: 'MS', title: '나의 가입 정보' },
  '/myt/join/product/fee-plan': { login: true, id: 'MS_05', title: '나의 요금제' },
  '/myt-join/myplanadd': { login: true, id: 'MS_06', title: '나의 부가상품' },
  '/myt-join/myplancombine': { login: true, id: 'MS_07', title: '나의 결합상품' },
  '/myt/join/product/fee-alarm': { login: true, id: 'MS_05_01', title: '요금제 변경 가능일 알람' },
  '/myt/join/product/fee-alarm/terminate': { login: true, id: 'MS_05_01_01', title: '요금제 변경 가능일 알림 서비스' },
  '/myt-join/myplancombine/infodiscount/month': { login: true, id: 'MS_09_01', title: '월별 상세 할인 내역' },
  '/myt/bill/guide': { login: true, id: 'MF_02_01', title: '요금안내서' },
  '/myt/bill/guide/call-gift': { login: true, id: 'MF_02_01_02', title: '요금안내서 콜기프트 사용요금 조회' },
  '/myt/bill/guide/roaming': { login: true, id: 'MF_02_01_03', title: '요금안내서 로밍 사용요금 조회' },
  '/myt/bill/guide/donation': { login: true, id: 'MF_02_01_04', title: '요금안내서 기부금/후원금 사용요금 조회' },
  '/myt/join/info/discount': { login: true, id: 'MS_09', title: '약정할인 및 단말 분할상환 정보' },
  '/myt-join/myplancombine/noagreement': { login: true, id: 'MS_08', title: '무약정 플랜포인트 내역' },
  '/myt-join/myinfo/contract': { login: true, id: 'MS_02_01', title: '이용계약 정보' },
  '/myt-join/wire/wiredo/sms': { login: true, id: 'MS_02_02', title: '망 작업 SMS 알림 신청' },
  '/myt-join/submain/wire/wirestopgo': { login: true, id: 'MS_04_03', title: '일시 정지/해제' },
  '/myt-join/submain/wire/modifyperiod': { login: true, id: 'MS_04_06', title: '약정기간 변경' },
  '/myt-join/submain/wire/changeowner': { login: true, id: 'MS_04_07', title: '명의 변경' },

  // MyT-data
  '/myt/data': { login: true, id: 'DC', title: '데이터/통화 관리' },
  '/myt-data/hotdata': { login: true, id: 'DC_01_01', title: '실시간 데이터 잔여량' },
  '/myt-data/submain/child-hotdata': { login: true, id: 'DC_08_01', title: '자녀 실시간 잔여량' },
  '/myt-data/hotdata/total-sharing': { login: true, id: 'DC_01_01_01', title: '통합공유 데이터' },
  '/myt-data/hotdata/cancel-tshare': { login: true, id: 'DC_01_01_02', title: 'T데이터 셰어링 USIM 해지' },
  '/myt-data/familydata': { login: true, id: 'DC_02', title: 'T가족모아 데이터' },
  '/myt/data/gift': { login: true, id: 'DC_03_01', title: 'T끼리 데이터 선물하기' },
  '/myt/data/ting': { login: true, id: 'DC_04_03', title: '팅요금제 충전 선물' },
  '/myt/data/cookiz': { login: true, id: 'DC_04_02', title: '팅/쿠키즈/안심음성 요' },
  '/myt/data/limit': { login: true, id: 'DC_04_01', title: '데이터 한도 요금제' },
  '/myt/data/recharge/coupon': { login: true, id: 'DC_05', title: '나의 리필쿠폰' },
  '/myt/data/recharge/coupon/use': { login: true, id: 'DC_05_01', title: '리필 쿠폰 사용' },
  '/myt-data/datainfo': { login: true, id: 'DC_07', title: '최근 충전/선물 내역' },

  // Product
  '/product/mobileplan': { login: false, id: 'MP', title: '모바일 요금제' },
  '/product/mobileplan-add': { login: false, id: 'MV', title: '부가서비스' },
  '/product/mobileplan/list': { login: false, id: 'MP_02', title: '모바일 요금제' },
  '/product/mobileplan-add/list': { login: false, id: 'MV_01', title: '부가서비스' },
  '/product/wireplan': { login: false, id: 'WP', title: '인터넷/전화/TV' },
  '/product/wireplan/internet': { login: false, id: 'WP_01', title: '인터넷' },
  '/product/wireplan/phone': { login: false, id: 'WP_01', title: '전화' },
  '/product/wireplan/tv': { login: false, id: 'WP_01', title: 'TV' },
  '/product/apps': { login: false, id: 'TA', title: 'T apps' },

  // Customer
  '/customer/agentsearch': { login: false, id: 'CS_02_01', title: '지점/대리점 찾기' },
  '/customer/agentsearch/detail': { login: false, id: 'CS_02_02', title: '매장정보' },
  '/customer/agentsearch/near': { login: true, id: 'CS_02_03', title: '내 위치와 가까운 매장' },
  '/customer/agentsearch/repair': { login: false, id: 'CS_03_01', title: 'AS센터 찾기' },
  '/customer/agentsearch/repair-detail': { login: false, id: 'CS_03_02', title: 'AS센터 정보' },
  '/customer/agentsearch/repair-manufacturer': { login: false, id: 'CS_03_03', title: '제조사 별 AS센터' },
  '/customer/document': { login: false, id: 'CS_09_01', title: '구비서류' },
  '/customer/faq': { login: false, id: 'CS_05_01', title: '자주 찾는 질문' },
  '/customer/faq/search': { login: false, id: 'CS_05_04', title: 'FAQ' },
  '/customer/helpline': { login: false, id: 'CS_14_01', title: '전화상담 예약하기' },
  '/customer/notice': { login: false, id: 'CS_10_01', title: '공지사항' },
  '/customer/svc-info/praise': { login: false, id: 'CS_11_01', title: '칭찬합니다' },
  '/customer/damage-info': { login: false, id: 'CS_13_01', title: '이용자 피해예방 센터' },
  '/customer/damage-info/guide': { login: false, id: 'CS_13_03', title: '이용자 피해예방 가이드' },
  '/customer/damage-info/warning': { login: false, id: 'CS_13_05', title: '최신 이용자 피해예방 주의보' },
  '/customer/damage-info/additions': { login: false, id: 'CS_13_07', title: '유용한 부가서비스' },
  '/customer/damage-info/related': { login: false, id: 'CS_13_08', title: '이용자 피해예방 관련 사이트' },

  // Benefit
  '/benefit/index': { login: false, id: 'BS', title: '혜택.할인 Index' },
  '/benefit/my-benefit': { login: false, id: 'BS_01', title: '나의 혜택 · 할인정보' },
  '/benefit/my/rainbowpoint': { login: true, id: 'BS_01_01', title: '레인보우 포인트' },
  '/benefit/my/rainbowpoint/adjustment': { login: true, id: 'BS_01_01_03', title: '포인트 합산' },
  '/benefit/my/rainbowpoint/transfer': { login: true, id: 'BS_01_01_04', title: '포인트 양도' },
  '/benefit/my-benefit/cookiz': { login: false, id: 'BS_01_01_06', title: '쿠키즈팅 포인트' },
  '/benefit/my-benefit/military': { login: false, id: 'BS_01_01_05', title: '현역플랜 포인트' },

  // Common
  '/common/member/tid-pwd': { login: false, id: 'CO_ME_01_04', title: '아이디 찾기/비밀번호 재설정' },
  '/common/member/manage': { login: true, id: 'CO_ME_01_05', title: '회원정보' },

  // Membership
  '/membership_benefit/mbrs_0001': { login: false, id: 'BE_03_01', title: '제휴브랜드' },
  '/membership/membership_info/mbrs_0001': { login: false, id: 'BE_04_01', title: '멤버십 카드 및 등급 안내' }
};
