apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bff-nodejs
  labels:
    app: bff-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-nodejs
  template:
    metadata:
      labels:
        app: bff-nodejs
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - bff-nodejs
              topologyKey: kubernetes.io/hostname
      containers:
      - name: bff-nodejs
        image: mtwd.icp.skt.com:8500/mtw-dev/bff-nodejs-mobile:1.0
        env:
        - name: REDIS_PWD_KEY
          valueFrom:
            secretKeyRef:
              name: encsecret
              key: jasyptEnc
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          requests:
            memory: "8192Mi"
          limits:
            memory: "8192Mi"
        volumeMounts:
        - mountPath: /tworld/uploads                  # (root)/uploads 에 volume mount
          name: upload-volume                            # volumes 의 name과 동일하게 설정
#        livenessProbe:
#          httpGet:
#            path: /api/health
#            port: 3000
#          initialDelaySeconds: 5
#          periodSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /api/health
#            port: 3000
#          initialDelaySeconds: 5
#          periodSeconds: 5
#      nodeSelector:
#        kubernetes.io/hostname: 211.188.180.74        # 74번 Host Node 에만 앱을 배포 (현재 74, 75 에 배포 가능)
      volumes:
      - name: upload-volume
        persistentVolumeClaim:
          claimName: upload-pvc