apiVersion: v1
kind: Service
metadata:
  name: bff-nodejs
spec:
  ports:
    - name: http
      port: 8080
      nodePort: 31011
      targetPort: 3000
  selector:
    app: bff-nodejs
  type: NodePort
