apiVersion: v1
kind: Service
metadata:
  name: bff-nodejs-mobile
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 3000
  selector:
    app: bff-nodejs-mobile
    version: '1.27'
  type: ClusterIP
