Tw.API_METHOD = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE'
};

Tw.API_VERSION = {
  V1: 'v1',
  V2: 'v2'
};

Tw.API_CMD = {
  BFF_LOGIN_ERROR: { path: '/core-auth/v1/login-histories', method: Tw.API_METHOD.POST},
  BFF_03_0003_C: { path: '/svc-catalog/detail', method: Tw.API_METHOD.GET },
  BFF_03_0004_C: { path: '/change-svc', method: Tw.API_METHOD.POST },
  BFF_03_0005_C: { path: '/selected-svc', method: Tw.API_METHOD.GET },
  BFF_03_0023_C: { path: '/core-recharge/:version/refill-gifts', method: Tw.API_METHOD.POST },

  // COMMON
  BFF_01_0006: { path: '/core-modification/:version/address/legal-dongs', method: Tw.API_METHOD.GET },
  BFF_01_0007: { path: '/core-modification/:version/address/legal-dongs', method: Tw.API_METHOD.GET },
  BFF_01_0008: { path: '/core-modification/:version/address/street-names', method: Tw.API_METHOD.GET },
  BFF_01_0009: { path: '/core-modification/:version/address/mailboxes', method: Tw.API_METHOD.GET },
  BFF_01_0010: { path: '/core-modification/:version/address/lot-numbers', method: Tw.API_METHOD.GET },
  BFF_01_0011: { path: '/core-modification/:version/address/buildings', method: Tw.API_METHOD.GET },
  BFF_01_0012: { path: '/core-modification/:version/address/standard', method: Tw.API_METHOD.GET },
  BFF_01_0013: { path: '/core-modification/:version/address/standard', method: Tw.API_METHOD.GET },
  BFF_01_0014: { path: '/core-auth/:version/auth-sms', method: Tw.API_METHOD.POST },
  BFF_01_0015: { path: '/:version/auth/skt-sms', method: Tw.API_METHOD.PUT },
  BFF_01_0016: { path: '/core-auth/:version/noti-sms', method: Tw.API_METHOD.POST },
  BFF_01_0017: { path: '/core-auth/:version/auth/email', method: Tw.API_METHOD.POST },
  BFF_01_0018: { path: '/:version/auth/email-authentication', method: Tw.API_METHOD.PUT },
  BFF_01_0019: { path: '/core-auth/:version/auth/motp', method: Tw.API_METHOD.POST },
  BFF_01_0020: { path: '/:version/auth/motp/auth', method: Tw.API_METHOD.POST },
  BFF_01_0021: { path: '/core-auth/:version/auth/motp', method: Tw.API_METHOD.GET },
  BFF_01_0026: { path: '/:version/cert/success', method: Tw.API_METHOD.POST },
  BFF_01_0027: { path: '/:version/pwd-cert-chk', method: Tw.API_METHOD.POST },
  BFF_01_0028: { path: '/core-auth/:version/auth-sms-finance', method: Tw.API_METHOD.POST },
  BFF_01_0029: { path: '/:version/auth/secure/client-key', method: Tw.API_METHOD.POST },
  BFF_01_0030: { path: '/:version/auth/secure/server-key', method: Tw.API_METHOD.POST },
  BFF_01_0031: { path: '/registrationrequestfromfc', method: Tw.API_METHOD.POST },
  BFF_01_0032: { path: '/registrationresponsefromfc', method: Tw.API_METHOD.POST },
  BFF_01_0033: { path: '/authenticationrequestfromfc', method: Tw.API_METHOD.POST },
  BFF_01_0034: { path: '/authenticationresponsefromfc', method: Tw.API_METHOD.POST },
  BFF_01_0035: { path: '/:version/cert/app', method: Tw.API_METHOD.POST },
  BFF_01_0036: { paht: '/:version/cert/info', method: Tw.API_METHOD.POST },
  BFF_01_0037: { path: '/core-auth/:version/auth-sms-corporation', method: Tw.API_METHOD.POST },
  BFF_01_0039: { path: '/:version/bpcp', method: Tw.API_METHOD.GET },
  BFF_01_0038: { path: '/deregistrationrequestfromfc', method: Tw.API_METHOD.POST },
  BFF_01_0043: { path: '/core-bill/:version/refund/refund-account-insert', method: Tw.API_METHOD.POST },
  BFF_01_0044: { path: '/core-bill/:version/refund/donation-insert', method: Tw.API_METHOD.POST },
  BFF_01_0045: { path: '/core-bill/:version/bill-pay/bank-list', method: Tw.API_METHOD.GET },
  BFF_01_0046: { path: '/core-modification/:version/uscan/file-upload', method: Tw.API_METHOD.POST },
  BFF_01_0049: { path: '/core-auth/:version/anonymous/exsms/apply', method: Tw.API_METHOD.POST },
  BFF_01_0051: { path: '/core-auth/:version/refund/skt-auth-sms/send', method: Tw.API_METHOD.POST },
  BFF_01_0052: { path: '/:version/refund/skt-auth-sms/confirm', method: Tw.API_METHOD.POST },
  BFF_01_0053: { path: '/:version/captcha/image', method: Tw.API_METHOD.GET },
  BFF_01_0054: { path: '/:version/captcha/audio', method: Tw.API_METHOD.GET },
  BFF_01_0055: { path: '/:version/captcha/answer/:args0', method: Tw.API_METHOD.PUT },
  BFF_01_0057: { path: '/:version/auth/skt-sms/representative', method: Tw.API_METHOD.POST },
  BFF_01_0058: { path: '/:version/auth/skt-sms/legal-agent', method: Tw.API_METHOD.POST },
  BFF_01_0059: { path: '/v1/auth/skt-sms/key-in', method: Tw.API_METHOD.POST },
  BFF_01_0061: { path: '/core-auth/:version/user-email', method: Tw.API_METHOD.GET },
  BFF_01_0063: { path: '/:version/auth/skt-sms/common', method: Tw.API_METHOD.PUT },
  BFF_01_0064: { path: '/:version/mask-methods', method: Tw.API_METHOD.GET },
  BFF_01_0065: { path: '/core-modification/:version/share-scuturl', method: Tw.API_METHOD.GET },
  // AUTH
  BFF_03_0002: { path: '/:version/user/account-auth-sessions', method: Tw.API_METHOD.POST },
  BFF_03_0003: { path: '/:version/user/accounts', method: Tw.API_METHOD.DELETE },
  BFF_03_0004: { path: '/core-auth/:version/services', method: Tw.API_METHOD.GET },
  BFF_03_0006: { path: '/:version/user/nick-names/:args0', method: Tw.API_METHOD.PUT },
  BFF_03_0007: { path: '/:version/user/tid-keys', method: Tw.API_METHOD.GET },
  BFF_03_0009: { path: '/:version/user/service-password-sessions', method: Tw.API_METHOD.POST },
  BFF_03_0010: { path: '/:version/user/locks', method: Tw.API_METHOD.DELETE },
  BFF_03_0011: { path: '/core-auth/:version/nationalities', method: Tw.API_METHOD.GET },
  BFF_03_0012: { path: '/:version/user/biz-auth-sessions', method: Tw.API_METHOD.POST },
  BFF_03_0013: { path: '/:version/user/biz-services', method: Tw.API_METHOD.POST },
  BFF_03_0014: { path: '/core-auth/:version/marketing-offer-subscriptions/:args0', method: Tw.API_METHOD.GET },
  BFF_03_0015: { path: '/core-auth/:version/marketing-offer-subscriptions/:args0', method: Tw.API_METHOD.PUT },
  BFF_03_0016: { path: '/:version/my-t/service-passwords', method: Tw.API_METHOD.PUT },
  BFF_03_0019: { path: '/core-auth/:version/users/:args0/otp', method: Tw.API_METHOD.POST },
  BFF_03_0020: { path: '/core-auth/:version/passwords-check', method: Tw.API_METHOD.GET },
  BFF_03_0021: { path: '/core-auth/:version/tworld-term-agreements', method: Tw.API_METHOD.GET },
  BFF_03_0022: { path: '/core-auth/:version/tworld-term-agreements', method: Tw.API_METHOD.PUT },
  BFF_03_0023: { path: '/core-auth/:version/t-noti-term-agreements', method: Tw.API_METHOD.GET },
  BFF_03_0024: { path: '/core-auth/:version/t-noti-term-agreements', method: Tw.API_METHOD.PUT },
  BFF_03_0025: { path: '/core-auth/:version/add-fcm-user-info', method: Tw.API_METHOD.POST },
  BFF_03_0026: { path: '/core-auth/:version/requestRegistFcmClickInfo', method: Tw.API_METHOD.POST },
  BFF_03_0027: { path: '/core-auth/:version/users/otp', method: Tw.API_METHOD.PUT },
  BFF_03_0028: { path: '/core-auth/:version/free-sms-availability/::args0', method: Tw.API_METHOD.GET },
  BFF_03_0029: { path: '/core-auth/:version/exposable-services', method: Tw.API_METHOD.GET },
  BFF_03_0030: { path: '/core-auth/:version/exposed-services', method: Tw.API_METHOD.GET },
  BFF_03_0032: { path: '/core-auth/:version/tworld-terms', method: Tw.API_METHOD.GET },

  // HOME
  BFF_04_0001: { path: '/core-membership/:version/card/homeinfo', method: Tw.API_METHOD.GET },
  BFF_04_0003: { path: '/core-modification/:version/quick-menu/saveInfo', method: Tw.API_METHOD.POST },
  BFF_04_0004: { path: '/core-auth/:version/get-fcm-push-list', method: Tw.API_METHOD.GET },
  BFF_04_0006: { path: '/core-bill/v1/use-contents/total-amt', method: Tw.API_METHOD.GET },
  BFF_04_0007: { path: '/core-bill/v1/micro-pay/total-amt', method: Tw.API_METHOD.GET },
  BFF_04_0008: { path: '/core-bill/v1/bill-pay/use-amt-main', method: Tw.API_METHOD.GET },
  BFF_04_0009: { path: '/core-bill/v1/bill-pay/bill-main', method: Tw.API_METHOD.GET },
  BFF_10_0178: { path: '/core-product/:version/mobiles/mls/recommend-product', method: Tw.API_METHOD.POST },


  // MYT
  BFF_05_0001: { path: '/:version/my-t/balances', method: Tw.API_METHOD.GET },
  BFF_05_0002: { path: '/core-balance/:version/balance-add-ons', method: Tw.API_METHOD.GET },
  BFF_05_0003: { path: '/core-balance/:version/troaming-sharings', method: Tw.API_METHOD.GET },
  BFF_05_0004: { path: '/core-balance/:version/data-sharings', method: Tw.API_METHOD.GET },
  BFF_05_0005: { path: '/core-balance/:version/tdata-sharings', method: Tw.API_METHOD.GET },
  BFF_05_0006: { path: '/core-balance/:version/data-top-up', method: Tw.API_METHOD.GET },
  BFF_05_0007: { path: '/core-balance/:version/ting', method: Tw.API_METHOD.GET },
  BFF_05_0008: { path: '/core-balance/:version/data-discount', method: Tw.API_METHOD.GET },
  BFF_05_0009: { path: '/core-balance/:version/data-sharings/child', method: Tw.API_METHOD.GET },
  BFF_05_0010: { path: '/core-balance/:version/children', method: Tw.API_METHOD.GET },
  BFF_05_0011: { path: '/core-balance/:version/tdata-sharings/:args0', method: Tw.API_METHOD.DELETE },
  BFF_05_0013: { path: '/core-bill/:version/pps-card', method: Tw.API_METHOD.GET },
  BFF_05_0014: { path: '/core-balance/:version/pps-histories', method: Tw.API_METHOD.GET },
  BFF_05_0020: { path: '/core-bill/:version/bill-pay/recent-bills', method: Tw.API_METHOD.GET },
  BFF_05_0021: { path: '/core-bill/:version/bill-pay/recent-usages', method: Tw.API_METHOD.GET },
  BFF_05_0022: { path: '/core-bill/:version/hotbills', method: Tw.API_METHOD.GET },
  BFF_05_0024: { path: '/core-bill/:version/child/children', method: Tw.API_METHOD.GET },
  BFF_05_0027: { path: '/core-bill/:version/bill-types', method: Tw.API_METHOD.PUT },
  BFF_05_0031: { path: '/core-bill/:version/bill-pay/payment-possible-day', method: Tw.API_METHOD.GET },
  BFF_05_0032: { path: '/core-bill/:version/bill-pay/payment-possible-day-input', method: Tw.API_METHOD.POST },
  BFF_05_0033: { path: '/core-bill/:version/bill-pay/autopay-schedule', method: Tw.API_METHOD.GET },
  BFF_05_0034: { path: '/core-bill/:version/bill-pay/suspension-cancel', method: Tw.API_METHOD.DELETE },
  // BFF_05_0035: { path: '/core-bill/:version/hotbill/fee/hotbill-request', method: Tw.API_METHOD.GET },
  BFF_05_0036: { path: '/core-bill/:version/bill-pay/bills', method: Tw.API_METHOD.GET },
  BFF_05_0038: { path: '/core-bill/:version/bill-pay/donation', method: Tw.API_METHOD.GET },
  BFF_05_0039_N: { path: '/core-bill/:version/bill-types-return', method: Tw.API_METHOD.GET },
  BFF_05_0040: { path: '/core-product/:version/services/wireless/addition/:args0', method: Tw.API_METHOD.GET },
  BFF_05_0044: { path: '/core-bill/:version/bill-pay/roaming', method: Tw.API_METHOD.GET },
  BFF_05_0045: { path: '/core-bill/:version/bill-pay/call-gift', method: Tw.API_METHOD.GET },
  BFF_05_0047: { path: '/core-bill/:version/bill-pay/used-amounts', method: Tw.API_METHOD.GET },
  BFF_05_0048: { path: '/core-bill/:version/bill-reissue', method: Tw.API_METHOD.POST },
  BFF_05_0050: { path: '/core-bill/:version/wire-bill-types', method: Tw.API_METHOD.PUT },
  BFF_05_0052: { path: '/core-bill/:version/wire-bill-reissue', method: Tw.API_METHOD.POST },
  BFF_05_0058: { path: '/core-bill/:version/accounts', method: Tw.API_METHOD.GET },
  BFF_05_0060: { path: '/core-modification/:version/no-contract-plan-points', method: Tw.API_METHOD.GET },
  BFF_05_0062: { path: '/core-modification/:version/wire-network-notification', method: Tw.API_METHOD.POST },
  BFF_05_0064: { path: '/core-bill/:version/use-contents/hist-requests', method: Tw.API_METHOD.GET },
  BFF_05_0066: { path: '/core-bill/:version/use-contents/limit-requests', method: Tw.API_METHOD.GET },
  BFF_05_0067: { path: '/core-bill/:version/use-contents/limit-up', method: Tw.API_METHOD.POST },
  BFF_05_0076: { path: '/core-modification/:version/myinfo/discount-infos-month', method: Tw.API_METHOD.GET },
  BFF_05_0078: { path: '/core-balance/:version/band-data-sharings', method: Tw.API_METHOD.GET },
  BFF_05_0079: { path: '/core-bill/:version/micro-pay/hist-requests', method: Tw.API_METHOD.POST },
  BFF_05_0080: { path: '/core-bill/:version/micro-pay/requests', method: Tw.API_METHOD.GET },
  BFF_05_0081: { path: '/core-bill/:version/micro-pay/requests', method: Tw.API_METHOD.POST },
  BFF_05_0082: { path: '/core-bill/:version/micro-pay/auto-set', method: Tw.API_METHOD.POST },
  BFF_05_0083: { path: '/core-bill/:version/micro-pay/requests', method: Tw.API_METHOD.PUT },
  BFF_05_0085: { path: '/core-bill/:version/micro-pay/password-status', method: Tw.API_METHOD.GET },
  BFF_05_0086: { path: '/core-bill/:version/micro-pay/password-create', method: Tw.API_METHOD.POST },
  BFF_05_0087: { path: '/core-bill/:version/micro-pay/password-changes', method: Tw.API_METHOD.PUT },
  BFF_05_0089: { path: '/core-bill/:version/prepayInfo', method: Tw.API_METHOD.GET },
  BFF_05_0091: { path: '/core-bill/:version/recent-usage-pattern', method: Tw.API_METHOD.GET },
  BFF_05_0093: { path: '/core-bill/:version/micro-pay/cphist-requests', method: Tw.API_METHOD.GET },
  BFF_05_0094: { path: '/core-modification/:version/combination-discounts', method: Tw.API_METHOD.GET },
  BFF_05_0096: { path: '/core-product/:version/benefit-suggestions', method: Tw.API_METHOD.GET },
  BFF_05_0106: { path: '/core-modification/:version/bill-discounts', method: Tw.API_METHOD.GET },
  BFF_05_0115: { path: '/core-bill/:version/cookiz-ting-points', method: Tw.API_METHOD.GET },
  BFF_05_0120: { path: '/core-bill/:version/military-service-points', method: Tw.API_METHOD.GET },
  BFF_05_0102: { path: '/core-bill/:version/rainbow-point-adjustments', method: Tw.API_METHOD.POST },
  BFF_05_0104: { path: '/core-bill/:version/rainbow-point-transfers', method: Tw.API_METHOD.POST },
  BFF_05_0105: { path: '/core-bill/:version/rainbow-point-transfers/:args0', method: Tw.API_METHOD.DELETE },
  BFF_05_0123: { path: '/core-product/:version/services/unavailableness', method: Tw.API_METHOD.GET },
  BFF_05_0100: { path: '/core-bill/:version/rainbow-point-histories', method: Tw.API_METHOD.GET },
  BFF_05_0121: { path: '/core-bill/:version/military-service-point-histories', method: Tw.API_METHOD.GET },
  BFF_05_0122: { path: '/core-bill/:version/cookiz-ting-point-histories', method: Tw.API_METHOD.GET },
  BFF_05_0126: { path: '/core-product/:version/fee-plans/change-notices', method: Tw.API_METHOD.POST },
  BFF_05_0127: { path: '/core-product/:version/fee-plans/change-notices', method: Tw.API_METHOD.DELETE },
  BFF_05_0129: { path: '/core-product/:version/services/wire/additions', method: Tw.API_METHOD.GET },
  BFF_05_0132: { path: '/core-bill/:version/rainbow-points', method: Tw.API_METHOD.GET },
  BFF_05_0133: { path: '/core-product/:version/services/combinations', method: Tw.API_METHOD.GET },
  BFF_05_0134: { path: '/core-product/:version/services/combinations/:args0', method: Tw.API_METHOD.GET },
  BFF_05_0135: { path: '/core-product/:version/services/combinations/data-benefits', method: Tw.API_METHOD.PUT },
  BFF_05_0137: { path: '/core-product/:version/services/wireless/additions', method: Tw.API_METHOD.GET },
  BFF_05_0136: { path: '/core-product/:version/services/wireless/fee-plans', method: Tw.API_METHOD.GET },
  BFF_05_0138: { path: '/core-product/:version/services/combinations/data-sharings', method: Tw.API_METHOD.PUT },
  BFF_05_0139: { path: '/core-modification/:version/myinfo/wire-service-contracts', method: Tw.API_METHOD.GET },
  BFF_05_0141: { path: '/core-modification/:version/wire-agreements-penalty', method: Tw.API_METHOD.GET },
  BFF_05_0142: { path: '/core-modification/:version/wire-agreements', method: Tw.API_METHOD.PUT },
  BFF_05_0144: { path: '/core-product/:version/services/combinations/:args0/terminations', method: Tw.API_METHOD.PUT },
  BFF_05_0147: { path: '/core-bill/:version/bill-address-change', method: Tw.API_METHOD.PUT },
  BFF_05_0149: { path: '/core-modification/:version/phone-pause-states', method: Tw.API_METHOD.GET },
  BFF_05_0150: { path: '/core-modification/:version/wire-troubles-cancel', method: Tw.API_METHOD.DELETE },
  BFF_05_0151: { path: '/:version/my-t/phone-pause-states', method: Tw.API_METHOD.POST },
  BFF_05_0152: { path: '/:version/my-t/phone-pause-states', method: Tw.API_METHOD.DELETE },
  BFF_05_0155: { path: '/core-modification/:version/myinfo/discount-info', method: Tw.API_METHOD.GET },
  BFF_05_0156: { path: '/core-modification/:version/wire-troubles', method: Tw.API_METHOD.GET },
  BFF_05_0158: { path: '/core-modification/:version/wire/penalty-info', method: Tw.API_METHOD.GET },
  BFF_05_0159: { path: '/core-modification/:version//wireInfo/listGiftProvide', method: Tw.API_METHOD.GET },
  BFF_05_0160: { path: '/core-modification/:version/myinfo/wire-free-call-check', method: Tw.API_METHOD.GET },
  BFF_05_0163: { path: '/core-modification/:version/myinfo/chg-wire-addr', method: Tw.API_METHOD.POST },
  BFF_05_0164: { path: '/core-modification/:version/wire-phone/chang-status', method: Tw.API_METHOD.GET },
  BFF_05_0165: { path: '/core-modification/:version/wire/change-request', method: Tw.API_METHOD.POST },
  BFF_05_0161: { path: '/core-product/:version/services/wireless/additions/cnt', method: Tw.API_METHOD.GET },
  BFF_05_0170: { path: '/core-modification/:version/myinfo/wire-set-pause', method: Tw.API_METHOD.POST },
  BFF_05_0171: { path: '/core-modification/:version/myinfo/wire-remove-pause', method: Tw.API_METHOD.POST },
  BFF_05_0172: { path: '/core-modification/:version/myinfo/get-wire-cancel-info', method: Tw.API_METHOD.GET },
  BFF_05_0173: { path: '/core-modification/:version/myinfo/get-wire-cancel-fee', method: Tw.API_METHOD.GET },
  BFF_05_0174: { path: '/core-modification/:version/myinfo/set-wire-cancel-service', method: Tw.API_METHOD.POST },
  BFF_05_0175: { path: '/core-bill/:version/no-contract-plan-points', method: Tw.API_METHOD.GET },
  BFF_05_0176: { path: '/core-bill/:version/micro-pay/requests-limit-down', method: Tw.API_METHOD.POST },
  BFF_05_0177: { path: '/core-bill/:version/use-contents/limit-down', method: Tw.API_METHOD.POST },
  BFF_05_0182: { path: '/core-modification/:version/new-number-notifications', method: Tw.API_METHOD.POST },
  BFF_05_0183: { path: '/core-modification/:version/new-number-notifications', method: Tw.API_METHOD.DELETE },
  BFF_05_0184: { path: '/core-modification/:version/number-change/search', method: Tw.API_METHOD.GET },
  BFF_05_0185: { path: '/core-modification/:version/number-change/process', method: Tw.API_METHOD.POST },
  BFF_05_0195: { path: '/core-modification/:version/longterm-phone-pause', method: Tw.API_METHOD.PUT },
  BFF_05_0196: { path: '/core-modification/:version/loyalty-benefits', method: Tw.API_METHOD.GET },
  BFF_05_0197: { path: '/core-modification/:version/longterm-phone-pause', method: Tw.API_METHOD.POST },
  BFF_05_0199: { path: '/core-bill/:version/bill-types-email', method: Tw.API_METHOD.PUT },
  BFF_05_0201: { path: '/core-balance/:version/troaming-data', method: Tw.API_METHOD.GET },
  BFF_05_0202: { path: '/core-balance/:version/troaming-like-home', method: Tw.API_METHOD.GET },
  BFF_05_0205: { path: '/core-bill/:version/use-contents/auth/hist-requests', method: Tw.API_METHOD.GET },
  BFF_05_0206: { path: '/core-bill/:version/micro-pay/auth/hist-requests', method: Tw.API_METHOD.POST },
  BFF_05_0207: { path: '/core-product/:version/services/combinations/:args0/personally-terminations', method: Tw.API_METHOD.PUT },

  // RECHARGE
  BFF_06_0001: { path: '/core-recharge/:version/refill-coupons', method: Tw.API_METHOD.GET },
  BFF_06_0002: { path: '/core-recharge/:version/refill-usages', method: Tw.API_METHOD.GET },
  BFF_06_0003: { path: '/core-recharge/:version/refill-gifts', method: Tw.API_METHOD.GET },
  BFF_06_0004: { path: '/core-gift/:version/regular-data-gifts', method: Tw.API_METHOD.POST },
  BFF_06_0005: { path: '/core-gift/:version/regular-data-gifts', method: Tw.API_METHOD.DELETE },
  BFF_06_0006: { path: '/core-gift/:version/regular-data-gifts', method: Tw.API_METHOD.GET },
  BFF_06_0007: { path: '/core-recharge/:version/refill-coupons', method: Tw.API_METHOD.PUT },
  BFF_06_0008: { path: '/core-recharge/:version/refill-gifts', method: Tw.API_METHOD.POST },
  BFF_06_0009: { path: '/core-recharge/:version/refill-options', method: Tw.API_METHOD.GET },
  BFF_06_0010: { path: '/core-recharge/:version/data-gift-requests', method: Tw.API_METHOD.GET },
  BFF_06_0011: { path: '/core-recharge/:version/data-gift-requests', method: Tw.API_METHOD.DELETE },
  BFF_06_0012: { path: '/core-recharge/:version/data-gift-request-receivers', method: Tw.API_METHOD.GET },
  BFF_06_0013: { path: '/core-recharge/:version/data-gift-requests', method: Tw.API_METHOD.GET },
  BFF_06_0014: { path: '/core-gift/:version/data-gift-balances', method: Tw.API_METHOD.GET },
  BFF_06_0015: { path: '/core-gift/:version/data-gift-senders', method: Tw.API_METHOD.GET },
  BFF_06_0016: { path: '/core-gift/:version/data-gifts', method: Tw.API_METHOD.POST },
  BFF_06_0017: { path: '/core-gift/:version/data-gift-messages', method: Tw.API_METHOD.POST },
  BFF_06_0018: { path: '/core-gift/:version/data-gifts', method: Tw.API_METHOD.GET },
  BFF_06_0019: { path: '/core-gift/:version/data-gift-receivers', method: Tw.API_METHOD.GET },
  BFF_06_0020: { path: '/core-recharge/:version/ting-gift-senders', method: Tw.API_METHOD.GET },
  BFF_06_0021: { path: '/core-recharge/:version/ting-gift-blocks', method: Tw.API_METHOD.POST },
  BFF_06_0022: { path: '/core-recharge/:version/ting-gift-receivers', method: Tw.API_METHOD.GET },
  BFF_06_0023: { path: '/core-recharge/:version/ting-gifts', method: Tw.API_METHOD.POST },
  BFF_06_0024: { path: '/core-recharge/:version/ting-press-benefiters', method: Tw.API_METHOD.POST },
  BFF_06_0025: { path: '/core-recharge/:version/ting-gift-requests', method: Tw.API_METHOD.POST },
  BFF_06_0026: { path: '/core-recharge/:version/ting-gifts', method: Tw.API_METHOD.GET },
  BFF_06_0027: { path: '/core-recharge/:version/ting-gift-blocks', method: Tw.API_METHOD.GET },
  BFF_06_0028: { path: '/core-recharge/:version/ting-subscriptions', method: Tw.API_METHOD.GET },
  BFF_06_0029: { path: '/core-recharge/:version/ting-top-ups', method: Tw.API_METHOD.POST },
  BFF_06_0030: { path: '/core-recharge/:version/regular-ting-top-ups', method: Tw.API_METHOD.POST },
  BFF_06_0031: { path: '/core-recharge/:version/regular-ting-top-ups', method: Tw.API_METHOD.DELETE },
  BFF_06_0032: { path: '/core-recharge/:version/ting-top-ups', method: Tw.API_METHOD.GET },
  BFF_06_0033: { path: '/core-recharge/:version/ting-permissions', method: Tw.API_METHOD.GET },
  BFF_06_0034: { path: '/core-recharge/:version/data-limitation-subscriptions', method: Tw.API_METHOD.GET },
  BFF_06_0035: { path: '/core-recharge/:version/regular-data-top-ups', method: Tw.API_METHOD.POST },
  BFF_06_0036: { path: '/core-recharge/:version/data-top-ups', method: Tw.API_METHOD.POST },
  BFF_06_0037: { path: '/core-recharge/:version/regular-data-top-ups', method: Tw.API_METHOD.DELETE },
  BFF_06_0038: { path: '/core-recharge/:version/data-limitations', method: Tw.API_METHOD.DELETE },
  BFF_06_0039: { path: '/core-recharge/:version/data-limitations', method: Tw.API_METHOD.POST },
  BFF_06_0040: { path: '/core-recharge/:version/regular-data-limitations', method: Tw.API_METHOD.DELETE },
  BFF_06_0041: { path: '/core-recharge/:version/regular-data-limitations', method: Tw.API_METHOD.POST },
  BFF_06_0042: { path: '/core-recharge/:version/data-top-ups', method: Tw.API_METHOD.GET },
  BFF_06_0043: { path: '/core-recharge/:version/data-limitations', method: Tw.API_METHOD.GET },
  BFF_06_0044: { path: '/core-balance/:version/tfamily-sharings', method: Tw.API_METHOD.GET },
  BFF_06_0045: { path: '/core-recharge/:version/tfamily-shareable-data', method: Tw.API_METHOD.GET },
  BFF_06_0046: { path: '/core-recharge/:version/tfamily-sharings', method: Tw.API_METHOD.POST },
  BFF_06_0048: { path: '/core-recharge/:version/regular-tfamily-sharings', method: Tw.API_METHOD.POST },
  BFF_06_0049: { path: '/core-recharge/:version/regular-tfamily-sharings', method: Tw.API_METHOD.DELETE },
  BFF_06_0050: { path: '/core-recharge/:version/tfamily-sharing-limitations', method: Tw.API_METHOD.POST },
  BFF_06_0051: { path: '/core-recharge/:version/tfamily-sharing-limitations/:args0', method: Tw.API_METHOD.DELETE },
  BFF_06_0052: { path: '/core-bill/:version/pps-cards', method: Tw.API_METHOD.POST },
  BFF_06_0053: { path: '/core-bill/:version/pps-credit-cards', method: Tw.API_METHOD.POST },
  BFF_06_0054: { path: '/core-bill/:version/pps-auto', method: Tw.API_METHOD.POST },
  BFF_06_0055: { path: '/core-bill/:version/pps-auto', method: Tw.API_METHOD.GET },
  BFF_06_0057: { path: '/core-bill/:version/pps-auto', method: Tw.API_METHOD.DELETE },
  BFF_06_0058: { path: '/core-bill/:version/pps-data', method: Tw.API_METHOD.POST },
  BFF_06_0059: { path: '/core-bill/:version/pps-data-auto', method: Tw.API_METHOD.POST },
  BFF_06_0060: { path: '/core-bill/:version/pps-data-auto', method: Tw.API_METHOD.GET },
  BFF_06_0061: { path: '/core-bill/:version/pps-data-auto', method: Tw.API_METHOD.DELETE },
  BFF_06_0062: { path: '/core-bill/:version/pps-recharges', method: Tw.API_METHOD.GET },
  BFF_06_0063: { path: '/core-bill/:version/pps-data-recharges', method: Tw.API_METHOD.GET },
  BFF_06_0064: { path: '/core-bill/:version/pps-alram', method: Tw.API_METHOD.POST },
  BFF_06_0065: { path: '/core-bill/:version/credit-cards', method: Tw.API_METHOD.GET },
  BFF_06_0066: { path: '/core-product/:version/gift-refill-products', method: Tw.API_METHOD.GET },
  BFF_06_0067: { path: '/core-bill/:version/pp-cards', method: Tw.API_METHOD.GET },
  BFF_06_0068: { path: '/core-recharge/:version/ting-permissions', method: Tw.API_METHOD.POST },
  BFF_06_0069: { path: '/core-bill/:version/pps-recharges', method: Tw.API_METHOD.DELETE },
  BFF_06_0070: { path: '/core-bill/:version/pps-data-recharges', method: Tw.API_METHOD.DELETE },
  BFF_06_0072: { path: '/core-recharge/:version/tfamily-cancelable-data', method: Tw.API_METHOD.GET },
  BFF_06_0073: { path: '/core-recharge/:version/tfamily-canceling-data', method: Tw.API_METHOD.GET },
  BFF_06_0074: { path: '/core-recharge/:version/tfamily-canceling', method: Tw.API_METHOD.POST },
  BFF_06_0075: { path: '/core-bill/v1/pps-alram', method: Tw.API_METHOD.GET },
  BFF_06_0076: { path: '/core-bill/v1/pps-alram', method: Tw.API_METHOD.DELETE },

  // PAYMENT
  BFF_07_0004: { path: '/core-bill/:version/cash-receipts-issue-history', method: Tw.API_METHOD.GET },
  BFF_07_0005: { path: '/core-bill/:version/point-autopays-history/cashback', method: Tw.API_METHOD.GET },
  BFF_07_0006: { path: '/core-bill/:version/point-autopays-history/tpoint', method: Tw.API_METHOD.GET },
  BFF_07_0007: { path: '/core-bill/:version/point-autopays-history/tpoint', method: Tw.API_METHOD.GET },
  BFF_07_0017: { path: '/core-bill/:version/bill-pay/tax-reprint', method: Tw.API_METHOD.GET },
  BFF_07_0018: { path: '/core-bill/:version/bill-pay/tax-reprint-email', method: Tw.API_METHOD.GET },
  BFF_07_0019: { path: '/core-bill/:version/bill-pay/tax-reprint-fax', method: Tw.API_METHOD.GET },
  BFF_07_0022: { path: '/core-bill/:version/bill-pay/autopay-banks', method: Tw.API_METHOD.GET },
  BFF_07_0023: { path: '/:version/payment/settle-pay-bank', method: Tw.API_METHOD.POST },
  BFF_07_0024: { path: '/core-bill/:version/bill-pay/cardnum-validation', method: Tw.API_METHOD.GET },
  BFF_07_0025: { path: '/:version/payment/settle-pay-card', method: Tw.API_METHOD.POST },
  BFF_07_0026: { path: '/core-bill/:version/bill-pay/settle-vbs', method: Tw.API_METHOD.GET },
  BFF_07_0027: { path: '/core-bill/:version/bill-pay/settle-vb-sms', method: Tw.API_METHOD.POST },
  BFF_07_0028: { path: '/core-bill/:version/bill-pay/avail-point-search', method: Tw.API_METHOD.GET },
  BFF_07_0029: { path: '/core-bill/:version/bill-pay/pay-ocb-tpoint-proc', method: Tw.API_METHOD.POST },
  BFF_07_0030: { path: '/core-bill/:version/payment/total-payment', method: Tw.API_METHOD.GET },
  BFF_07_0032: { path: '/core-bill/:version/payment/over-payment-refund-account', method: Tw.API_METHOD.POST },
  BFF_07_0035: { path: '/core-bill/:version/payment/realtime-payment', method: Tw.API_METHOD.GET },
  BFF_07_0036: { path: '/core-bill/:version/payment/realtime-payment-detail', method: Tw.API_METHOD.GET },
  BFF_07_0037: { path: '/core-bill/:version/payment/auto-payment', method: Tw.API_METHOD.GET },
  BFF_07_0038: { path: '/core-bill/:version/bill-pay/donation', method: Tw.API_METHOD.GET },
  BFF_07_0039: { path: '/core-bill/:version/payment/auto-integrated-account-payment', method: Tw.API_METHOD.GET },
  BFF_07_0040: { path: '/core-bill/:version/payment/auto-integrated-payment-cancle-request', method: Tw.API_METHOD.POST },
  BFF_07_0041: { path: '/core-bill/:version/ocbcard-info-check-show', method: Tw.API_METHOD.GET },
  BFF_07_0042: { path: '/core-bill/:version/rainbow-point-check-show', method: Tw.API_METHOD.GET },
  BFF_07_0043: { path: '/core-bill/:version/ocbcard-no-info', method: Tw.API_METHOD.GET },
  BFF_07_0045: { path: '/core-bill/:version/ocb-point-onetime-reserve', method: Tw.API_METHOD.POST },
  BFF_07_0047: { path: '/core-bill/:version/ocb-point-onetime-cancel', method: Tw.API_METHOD.POST },
  BFF_07_0048: { path: '/core-bill/:version/rainbow-point-onetime-reserve', method: Tw.API_METHOD.POST },
  BFF_07_0050: { path: '/core-bill/:version/rainbow-point-onetime-cancel', method: Tw.API_METHOD.POST },
  BFF_07_0054: { path: '/core-bill/:version/ocb-point-autopay-modify', method: Tw.API_METHOD.POST },
  BFF_07_0056: { path: '/core-bill/:version/rainbow-point-autopay-change', method: Tw.API_METHOD.POST },
  BFF_07_0058: { path: '/core-bill/:version/ocb-point-onetime-history', method: Tw.API_METHOD.GET },
  BFF_07_0059: { path: '/core-bill/:version/rainbow-point-onetime-history', method: Tw.API_METHOD.GET },
  BFF_07_0060: { path: '/core-bill/:version/auto-payments', method: Tw.API_METHOD.GET },
  BFF_07_0061: { path: '/:version/auto-payments', method: Tw.API_METHOD.POST },
  BFF_07_0062: { path: '/:version/auto-payments', method: Tw.API_METHOD.PUT },
  BFF_07_0063: { path: '/core-bill/:version/auto-payments', method: Tw.API_METHOD.DELETE },
  BFF_07_0064: { path: '/core-bill/:version/autopay/db-req', method: Tw.API_METHOD.POST },
  BFF_07_0065: { path: '/core-bill/:version/autopay/pay-cycl-chg', method: Tw.API_METHOD.PUT },
  BFF_07_0068: { path: '/core-bill/:version/autopay/card-info', method: Tw.API_METHOD.GET },
  BFF_07_0069: { path: '/core-bill/:version/payment/auto-integrated-payment/cancel', method: Tw.API_METHOD.GET },
  BFF_07_0071: { path: '/core-bill/:version/micro-prepay/hist-requests', method: Tw.API_METHOD.GET },
  BFF_07_0073: { path: '/core-bill/:version/micro-prepay/requests', method: Tw.API_METHOD.GET },
  BFF_07_0074: { path: '/core-bill/:version/micro-prepay/process', method: Tw.API_METHOD.POST },
  BFF_07_0075: { path: '/core-bill/:version/micro-prepay/auto-list', method: Tw.API_METHOD.GET },
  BFF_07_0076: { path: '/core-bill/:version/micro-prepay/auto-process', method: Tw.API_METHOD.POST },
  BFF_07_0077: { path: '/core-bill/:version/micro-prepay/auto-delete', method: Tw.API_METHOD.POST },
  BFF_07_0078: { path: '/core-bill/:version/use-contents-prepay/hist-requests', method: Tw.API_METHOD.GET },
  BFF_07_0079: { path: '/core-bill/:version/use-contents-prepay/auto-hist', method: Tw.API_METHOD.GET },
  BFF_07_0081: { path: '/core-bill/:version/use-contents-prepay/requests', method: Tw.API_METHOD.GET },
  BFF_07_0082: { path: '/core-bill/:version/use-contents-prepay/process', method: Tw.API_METHOD.POST },
  BFF_07_0083: { path: '/core-bill/:version/use-contents-prepay/auto-process', method: Tw.API_METHOD.POST },
  BFF_07_0084: { path: '/core-bill/:version/use-contents-prepay/auto-delete', method: Tw.API_METHOD.POST },
  BFF_07_0087: { path: '/core-bill/:version/ocb-point-pay', method: Tw.API_METHOD.POST },
  BFF_07_0088: { path: '/core-bill/:version/payment/over-payment-refund-account', method: Tw.API_METHOD.POST },

  //CUSTOMER
  BFF_08_0001: { path: '/core-modification/:version/counsel-time-check', method: Tw.API_METHOD.GET },
  BFF_08_0002: { path: '/core-modification/:version/counsel-reserve', method: Tw.API_METHOD.POST },
  BFF_08_0003: { path: '/core-modification/:version/counsel-histories', method: Tw.API_METHOD.GET },
  BFF_08_0004: { path: '/core-modification/:version/region-store-list', method: Tw.API_METHOD.GET },
  BFF_08_0005: { path: '/core-modification/:version/region-addr-list', method: Tw.API_METHOD.GET },
  BFF_08_0006: { path: '/core-modification/:version/region-subway-list', method: Tw.API_METHOD.GET },
  BFF_08_0008: { path: '/core-modification/:version/region-close-store-list', method: Tw.API_METHOD.GET },
  BFF_08_0009: { path: '/core-modification/:version/voice-certification-check', method: Tw.API_METHOD.GET },
  BFF_08_0010: { path: '/core-modification/:version/email-inquiry-categories', method: Tw.API_METHOD.GET },
  BFF_08_0012: { path: '/core-modification/:version/email-inquiry/append-inquiry', method: Tw.API_METHOD.POST },
  BFF_08_0013: { path: '/core-modification/:version/email-inquiry', method: Tw.API_METHOD.POST },
  BFF_08_0014: { path: '/:version/cs/file-upload', method: Tw.API_METHOD.POST },
  BFF_08_0015: { path: '/core-modification/:version/brand-phone-list', method: Tw.API_METHOD.GET },
  BFF_08_0016: { path: '/core-modification/:version/direct-shop/order-list', method: Tw.API_METHOD.GET },
  BFF_08_0020: { path: '/core-modification/:version/inquiry-direct-shop', method: Tw.API_METHOD.POST },
  BFF_08_0021: { path: '/core-modification/:version/inquiry-chocolate', method: Tw.API_METHOD.POST },
  BFF_08_0025: { path: '/core-modification/:version/survey/surveyMainBanner', method: Tw.API_METHOD.GET },
  BFF_08_0026: { path: '/core-modification/:version/guide/categories', method: Tw.API_METHOD.GET },
  BFF_08_0028: { path: '/core-modification/:version/notice/tworld-submain', method: Tw.API_METHOD.GET },
  BFF_08_0029: { path: '/core-modification/:version/notice-tworld', method: Tw.API_METHOD.GET },
  BFF_08_0031: { path: '/core-modification/:version/notice-membership', method: Tw.API_METHOD.GET },
  BFF_08_0033: { path: '/core-modification/:version/prevent/notice', method: Tw.API_METHOD.GET },
  BFF_08_0034: { path: '/core-modification/:version/voice-certification', method: Tw.API_METHOD.POST },
  BFF_08_0035: { path: '/core-modification/:version/survey/surveyJoin', method: Tw.API_METHOD.POST },
  BFF_08_0036: { path: '/core-modification/:version/survey/surveyJoinQstn', method: Tw.API_METHOD.POST },
  BFF_08_0039: { path: '/core-modification/:version/notice-direct', method: Tw.API_METHOD.GET },
  BFF_08_0040: { path: '/core-modification/:version/notice-roaming', method: Tw.API_METHOD.GET },
  BFF_08_0042: { path: '/core-modification/:version/email-inquiry/service-mobile', method: Tw.API_METHOD.POST },
  BFF_08_0043: { path: '/core-modification/:version/email-inquiry/service-internet', method: Tw.API_METHOD.POST },
  BFF_08_0044: { path: '/core-modification/:version/email-inquiry/quality-mobile', method: Tw.API_METHOD.POST },
  BFF_08_0045: { path: '/core-modification/:version/email-inquiry/quality-internet', method: Tw.API_METHOD.POST },
  BFF_08_0050: { path: '/core-modification/:version/ifaq/iFaqList', method: Tw.API_METHOD.GET },
  BFF_08_0051: { path: '/core-modification/:version/ifaq/iFaq-category-List', method: Tw.API_METHOD.GET },
  BFF_08_0052: { path: '/core-modification/:version/ifaq/iFaqList-Cate', method: Tw.API_METHOD.GET },
  BFF_08_0054: { path: '/core-modification/:version/require-document/reqDocument', method: Tw.API_METHOD.GET },
  BFF_08_0056: { path: '/core-modification/:version/guide/use-detail', method: Tw.API_METHOD.GET },
  BFF_08_0057: { path: '/core-modification/:version/guide/site-use', method: Tw.API_METHOD.GET },
  BFF_08_0058: { path: '/core-modification/:version/praise/savePraiseInfo', method: Tw.API_METHOD.POST },
  BFF_08_0059: { path: '/core-modification/:version/term/access-terms', method: Tw.API_METHOD.GET },

  BFF_08_0060: { path: '/core-modification/:version/email-inquiry-list', method: Tw.API_METHOD.GET },
  BFF_08_0061: { path: '/core-modification/:version/email-inquiry-detail', method: Tw.API_METHOD.GET },
  BFF_08_0062: { path: '/core-modification/:version/email-inquiry', method: Tw.API_METHOD.DELETE },
  BFF_08_0063: { path: '/core-modification/v1/guide/contents-list', method: Tw.API_METHOD.GET },

  BFF_08_0064: { path: '/core-modification/:version/guide/contents-detail/:args0', method: Tw.API_METHOD.GET },

  //SEARCH SURVEY
  BFF_08_0071: { path: '/core-modification/:version/search/invst-append', method: Tw.API_METHOD.POST },
  BFF_08_0072: { path: '/core-modification/:version/search/invst-insert', method: Tw.API_METHOD.POST },

  BFF_08_0075: { path: '/core-auth/:version/autosms/sendAutoSMSAuthNum', method: Tw.API_METHOD.POST },
  BFF_08_0076: { path: '/:version/autosms/skt-sms/confirm', method: Tw.API_METHOD.POST },

  // EVENT
  BFF_09_0001: { path: '/core-membership/:version/event/ing-list', method: Tw.API_METHOD.GET },
  BFF_09_0002: { path: '/core-membership/:version/event/detail/:args0', method: Tw.API_METHOD.GET },
  BFF_09_0003: { path: '/core-membership/:version/event/old-list', method: Tw.API_METHOD.GET },
  BFF_09_0004: { path: '/core-membership/:version/event/win-list', method: Tw.API_METHOD.GET },
  BFF_09_0005: { path: '/core-membership/:version/event/win-detail/:args0', method: Tw.API_METHOD.GET },

  // PRODUCT
  BFF_10_0001: { path: '/core-product/:version/ledger/:args0', method: Tw.API_METHOD.GET },
  BFF_10_0007: { path: '/core-product/:version/mobiles/fee-plans/:args0/joins/join-prechecks', method: Tw.API_METHOD.GET },
  BFF_10_0008: { path: '/:version/products/fee-plans/:args0/join-term-infos', method: Tw.API_METHOD.GET },
  BFF_10_0010: { path: '/core-product/:version/mobiles/fee-plans/joins/over-chargings', method: Tw.API_METHOD.GET },
  BFF_10_0012: { path: '/:version/products/fee-plans/:args0/joins', method: Tw.API_METHOD.PUT },
  BFF_10_0013: { path: '/core-product/:version/mobiles/fee-plans/:args0/tplan-sets', method: Tw.API_METHOD.GET },
  BFF_10_0014: { path: '/core-product/:version/mobiles/fee-plans/:args0/tplan-sets', method: Tw.API_METHOD.PUT },
  BFF_10_0015: { path: '/core-product/:version/mobiles/fee-plans/:args0/tplan-benefits', method: Tw.API_METHOD.GET },
  BFF_10_0017: { path: '/:version/products/additions/:args0/join-term-infos', method: Tw.API_METHOD.GET },
  BFF_10_0018: { path: '/core-product/:version/mobiles/additions-set/:args0/joins', method: Tw.API_METHOD.POST },
  BFF_10_0019: { path: '/core-product/:version/mobiles/additions-sets/:args0/sets/lines', method: Tw.API_METHOD.DELETE },
  BFF_10_0020: { path: '/core-product/:version/mobiles/additions-sets/:args0/sets/lines', method: Tw.API_METHOD.POST },
  BFF_10_0021: { path: '/core-product/:version/mobiles/additions-sets/:args0/sets', method: Tw.API_METHOD.GET },
  BFF_10_0022: { path: '/core-product/:version/mobiles/additions-sets/:args0', method: Tw.API_METHOD.DELETE },
  BFF_10_0031: { path: '/core-product/:version/submain/products', method: Tw.API_METHOD.GET },
  BFF_10_0032: { path: '/core-product/:version/submain/filters', method: Tw.API_METHOD.GET },
  BFF_10_0034: { path: '/core-product/:version/mobiles/fee-plans/young-plan-sets', method: Tw.API_METHOD.GET },
  BFF_10_0035: { path: '/core-product/:version/mobiles/additions/:args0/joins', method: Tw.API_METHOD.POST },
  BFF_10_0036: { path: '/core-product/:version/mobiles/additions/:args0', method: Tw.API_METHOD.DELETE },
  BFF_10_0037: { path: '/core-product/:version/mobiles/fee-plans/t-tab-sets', method: Tw.API_METHOD.GET },
  BFF_10_0038: { path: '/core-product/:version/mobiles/additions/:args0/vas-terms', method: Tw.API_METHOD.GET },
  BFF_10_0039: { path: '/core-product/:version/combinations/discount-simulation', method: Tw.API_METHOD.GET },
  BFF_10_0041: { path: '/core-product/:version/mobiles/fee-plans/ting-sets', method: Tw.API_METHOD.PUT },
  BFF_10_0043: { path: '/core-product/:version/mobiles/fee-plans/zone-sets', method: Tw.API_METHOD.GET },
  BFF_10_0044: { path: '/core-product/:version/mobiles/fee-plans/zones', method: Tw.API_METHOD.GET },
  BFF_10_0045: { path: '/core-product/:version/mobiles/fee-plans/zone-sets', method: Tw.API_METHOD.PUT },
  BFF_10_0046: { path: '/:version/products/fee-plans/:args0/option-sets', method: Tw.API_METHOD.POST },
  BFF_10_0048: { path: '/core-modification/:version/wireJoin/listUseAddressService', method: Tw.API_METHOD.POST },
  BFF_10_0054: { path: '/core-product/:version/submain/benefit-discount-products', method: Tw.API_METHOD.GET },
  BFF_10_0056: { path: '/core-product/:version/services/roaming/fee-plans', method: Tw.API_METHOD.GET },
  BFF_10_0065: { path: '/core-product/:version/roaming/tpie-reservation', method: Tw.API_METHOD.POST },
  BFF_10_0066: { path: '/core-product/:version/roaming/tpie-reservation', method: Tw.API_METHOD.PUT },
  BFF_10_0067: { path: '/core-product/:version/roaming/tpie', method: Tw.API_METHOD.GET },
  BFF_10_0068: { path: '/core-product/:version/roaming/tpie-reservation', method: Tw.API_METHOD.GET },
  BFF_10_0071: { path: '/core-product/:version/mobiles/fee-plans/num-couple-sets', method: Tw.API_METHOD.PUT },
  BFF_10_0073: { path: '/core-product/:version/mobiles/fee-plans/snum-sets', method: Tw.API_METHOD.GET },
  BFF_10_0074: { path: '/core-product/:version/mobiles/fee-plans/snum-sets', method: Tw.API_METHOD.PUT },
  BFF_10_0076: { path: '/core-product/:version/wire/joins/counsel', method: Tw.API_METHOD.POST },
  BFF_10_0078: { path: '/core-product/:version/combinations/necessary-documents/inspects', method: Tw.API_METHOD.GET },
  BFF_10_0082: { path: '/core-product/:version/mobiles/additions-sets/:args0/tplusdis-sets', method: Tw.API_METHOD.POST },
  BFF_10_0083: { path: '/core-product/:version/mobiles/additions-sets/:args0/tplusdis-sets', method: Tw.API_METHOD.DELETE },
  BFF_10_0093: { path: '/core-product/:version/submain/tapps', method: Tw.API_METHOD.GET },
  BFF_10_0099: { path: '/core-product/:version/wire/additions/:args0/joins', method: Tw.API_METHOD.POST },
  BFF_10_0100: { path: '/core-product/:version/wire/additions/:args0/joins', method: Tw.API_METHOD.DELETE },
  BFF_10_0109: { path: '/core-product/:version/services/wire/addition/:args0', method: Tw.API_METHOD.GET },
  BFF_10_0113: {
    path: '/core-product/:version/services/combinations/:args0/terminations/prechecks',
    method: Tw.API_METHOD.GET
  },
  BFF_10_0119: { path: '/core-product/:version/services/combinations/:args0/scrbcheck', method: Tw.API_METHOD.GET },
  BFF_10_0137: { path: '/core-product/:version/wire/additions/:args0/joins', method: Tw.API_METHOD.PUT },
  BFF_10_0138: { path: '/core-product/:version/wire/additions/:args0/joins/reservations', method: Tw.API_METHOD.DELETE },
  BFF_10_0142: { path: '/core-product/:version/mobiles/combinations/:args0/joins/services', method: Tw.API_METHOD.GET },
  BFF_10_0143: { path: '/core-product/:version/mobiles/combinations/:args0/joins/simulations', method: Tw.API_METHOD.GET },
  BFF_10_0144: { path: '/core-product/:version/mobiles/combinations/:args0/joins', method: Tw.API_METHOD.POST },
  BFF_10_0151: { path: '/core-product/:version/mobiles/fee-plans/:args0/joins/term-prechecks', method: Tw.API_METHOD.GET },
  BFF_10_0164: { path: '/core-product/:version/wire/additions/:args0/joins/ledger-prechecks/joins', method: Tw.API_METHOD.GET },
  BFF_10_0165: { path: '/core-product/:version/wire/additions/:args0/joins/ledger-prechecks/sets', method: Tw.API_METHOD.GET },
  BFF_10_0166: { path: '/core-product/:version/wire/additions/:args0/joins/ledger-prechecks/cancels', method: Tw.API_METHOD.GET },
  BFF_10_0167: { path: '/core-product/:version/wire/additions/:args0/joins/ledger-prechecks/adds', method: Tw.API_METHOD.GET },
  BFF_10_0168: { path: '/core-product/:version/wire/additions/:args0/joins/ledger-prechecks/terms', method: Tw.API_METHOD.GET },
  BFF_10_0169: { path: '/core-product/:version/mobiles/fee-plans/young-plan-mid-sets', method: Tw.API_METHOD.GET },
  BFF_10_0170: { path: '/core-product/:version/mobiles/fee-plans/young-plan-mid-sets', method: Tw.API_METHOD.PUT },
  BFF_10_0171: { path: '/core-product/:version/mobiles/combinations/tfamilymoa/join/prechecks', method: Tw.API_METHOD.GET },
  BFF_10_0172: { path: '/core-product/:version/mobiles/combinations/tfamilymoa/join/oppsblcheck', method: Tw.API_METHOD.GET },
  BFF_10_0173: { path: '/core-product/:version/mobiles/combinations/tfamilymoa/join', method: Tw.API_METHOD.POST },
  BFF_10_0174: { path: '/core-product/:version/roaming/auto-dial', method: Tw.API_METHOD.GET },
  BFF_10_0175: { path: '/core-product/:version/roaming/fee-plans/:args0/prechecks', method: Tw.API_METHOD.GET },
  BFF_10_0176: { path: '/core-product/:version/mobiles/additions-sets/addressid-sets', method: Tw.API_METHOD.POST },
  BFF_10_0181: { path: '/core-product/:version/mobiles/additions/:args0/send-sms', method: Tw.API_METHOD.GET },

  // ROAMING
  BFF_10_0000: { path: '/core-product/:version/submain/products', method: Tw.API_METHOD.GET },
  BFF_10_0058: { path: '/core-product/:version/roaming/country-rate', method: Tw.API_METHOD.GET },
  BFF_10_0059: { path: '/core-product/:version/roaming/modelCode-srch', method: Tw.API_METHOD.GET },
  BFF_10_0060: { path: '/core-product/:version/roaming/country-srch', method: Tw.API_METHOD.GET },
  BFF_10_0061: { path: '/core-product/:version/roaming/ManageType-srch', method: Tw.API_METHOD.GET },
  BFF_10_0084: { path: '/core-product/:version/roaming/fee-plans/:args0/joins', method: Tw.API_METHOD.POST },
  BFF_10_0085: { path: '/core-product/:version/roaming/fee-plans/:args0/sets', method: Tw.API_METHOD.PUT },
  BFF_10_0086: { path: '/core-product/:version/roaming/fee-plans/:args0/terminations', method: Tw.API_METHOD.DELETE },
  BFF_10_0092: { path: '/core-product/:version/roaming/services/t-roam-tog/:args0/members', method: Tw.API_METHOD.POST },

  // MEMBERSHIP
  BFF_11_0001: { path: '/core-membership/:version/card/home', method: Tw.API_METHOD.GET },
  BFF_11_0002: { path: '/core-membership/:version/card/info', method: Tw.API_METHOD.GET },
  BFF_11_0003: { path: '/core-membership/:version/card-reissue-info', method: Tw.API_METHOD.GET },
  BFF_11_0004: { path: '/core-membership/:version/card-reissue-process', method: Tw.API_METHOD.PUT },
  BFF_11_0005: { path: '/core-membership/:version/card-reissue-cancel-process', method: Tw.API_METHOD.PUT },
  BFF_11_0006: { path: '/core-membership/:version/card/change', method: Tw.API_METHOD.PUT },
  BFF_11_0007: { path: '/core-membership/:version/card/check', method: Tw.API_METHOD.GET },
  BFF_11_0009: { path: '/core-membership/:version/card/used-list', method: Tw.API_METHOD.GET },
  BFF_11_0010: { path: '/core-membership/:version/card/hist', method: Tw.API_METHOD.GET },
  BFF_11_0011: { path: '/core-membership/:version/card/create', method: Tw.API_METHOD.POST },
  BFF_11_0012: { path: '/core-membership/:version/card/modify', method: Tw.API_METHOD.PUT },
  BFF_11_0013: { path: '/core-membership/:version/card/cancel-info', method: Tw.API_METHOD.GET },
  BFF_11_0014: { path: '/core-membership/:version/card/cancel', method: Tw.API_METHOD.PUT },
  BFF_11_0015: { path: '/core-membership/:version/card/create-check', method: Tw.API_METHOD.GET },
  BFF_11_0016: { path: '/core-membership/:version/tmembership/cate-list', method: Tw.API_METHOD.GET },
  BFF_11_0017: { path: '/core-membership/:version/tmembership/brand-list', method: Tw.API_METHOD.GET },
  BFF_11_0019: { path: '/core-membership/:version/tmembership/brand-like', method: Tw.API_METHOD.POST },
  BFF_11_0020: { path: '/core-membership/:version/tmembership/brand-dislike', method: Tw.API_METHOD.POST },
  BFF_11_0021: { path: '/core-membership/:version/tmembership/area1-list', method: Tw.API_METHOD.GET },
  BFF_11_0022: { path: '/core-membership/:version/tmembership/area2-list', method: Tw.API_METHOD.GET },
  BFF_11_0023: { path: '/core-membership/:version/tmembership/mrcht-list', method: Tw.API_METHOD.GET },
  BFF_11_0024: { path: '/core-membership/:version/tmembership/mrcht-info', method: Tw.API_METHOD.GET },
  BFF_11_0025: { path: '/core-membership/:version/tmembership/near-brand', method: Tw.API_METHOD.GET },
  BFF_11_0026: { path: '/core-membership/:version/tmembership/area-by-geo', method: Tw.API_METHOD.GET },
  BFF_10_0062: { path: '/core-product/:version/mobiles/additions-sets/:args0/seldis-sets', method: Tw.API_METHOD.GET },
  BFF_10_0063: { path: '/core-product/:version/mobiles/additions-sets/:args0/seldis-sets', method: Tw.API_METHOD.POST },

  //SEARCH
  SEARCH_AUTO_COMPLETE: { path: '/search/tworld/autocomplete', method: Tw.API_METHOD.GET },
  STACK_SEARCH_USER_CLICK: { path: '/search/tworld/log/save', method: Tw.API_METHOD.GET },

  // TEST
  GET: { path: '/posts', method: Tw.API_METHOD.GET },
  GET_PARAM: { path: '/comments', method: Tw.API_METHOD.GET },
  GET_PATH_PARAM: { path: '/posts/:args0', method: Tw.API_METHOD.GET },
  POST: { path: '/posts', method: Tw.API_METHOD.POST },
  POST_PARAM: { path: '/posts', method: Tw.API_METHOD.POST },
  PUT: { path: '/posts/1', method: Tw.API_METHOD.PUT },
  PUT_PARAM: { path: '/posts/1', method: Tw.API_METHOD.PUT },
  DELETE: { path: '/posts/1', method: Tw.API_METHOD.DELETE },
  DELETE_PARAM: {}
};

Tw.NODE_CMD = {
  GET_ENVIRONMENT: { path: '/environment', method: Tw.API_METHOD.GET },
  GET_DOMAIN: { path: '/domain', method: Tw.API_METHOD.GET },
  LOGIN_TID: { path: '/user/sessions', method: Tw.API_METHOD.POST },
  LOGOUT_TID: { path: '/logout-tid', method: Tw.API_METHOD.POST },
  SESSION: { path: '/session', method: Tw.API_METHOD.POST },
  EASY_LOGIN_AOS: { path: '/user/login/android', method: Tw.API_METHOD.POST },
  EASY_LOGIN_IOS: { path: '/user/login/ios', method: Tw.API_METHOD.POST },
  CHANGE_SESSION: { path: '/common/selected-sessions', method: Tw.API_METHOD.POST },
  LOGIN_SVC_PASSWORD: { path: '/user/service-password-sessions', method: Tw.API_METHOD.POST },
  LOGIN_USER_LOCK: { path: '/user/locks', method: Tw.API_METHOD.DELETE },
  CHANGE_SVC_PASSWORD: { path: '/my-t/service-passwords', method: Tw.API_METHOD.POST },
  CHANGE_LINE: { path: '/user/services', method: Tw.API_METHOD.POST },
  CHANGE_NICKNAME: { path: '/user/nick-names', method: Tw.API_METHOD.POST },
  UPDATE_SVC: { path: '/common/selected-sessions', method: Tw.API_METHOD.GET },

  UPLOAD_FILE: { path: '/uploads', method: Tw.API_METHOD.POST },
  GET_SVC_INFO: { path: '/svcInfo', method: Tw.API_METHOD.GET },
  GET_ALL_SVC: { path: '/allSvcInfo', method: Tw.API_METHOD.GET },
  GET_CHILD_INFO: { path: '/childInfo', method: Tw.API_METHOD.GET },
  UPDATE_NOTICE_TYPE: { path: '/update/notice-type', method: Tw.API_METHOD.PUT },

  GET_VERSION: { path: '/app-version', method: Tw.API_METHOD.GET },
  GET_SPLASH: { path: '/splash', method: Tw.API_METHOD.GET },
  GET_APP_NOTICE: { path: '/app-notice', method: Tw.API_METHOD.GET },
  GET_XTINFO: { path: '/xtractor-info', method: Tw.API_METHOD.GET },
  GET_DOWNGRADE: { path: '/downgrade', method: Tw.API_METHOD.GET },

  GET_URL_META: { path: '/urlMeta', method: Tw.API_METHOD.GET },
  GET_MENU: { path: '/menu', method: Tw.API_METHOD.GET },
  GET_MENU_RCMD: { path: '/menu-rcmd', method: Tw.API_METHOD.GET },
  GET_BANNER_ADMIN: { path: '/banner/admin', method: Tw.API_METHOD.GET },
  GET_BANNER_TOS: { path: '/banner/tos', method: Tw.API_METHOD.GET },
  GET_NEW_BANNER_TOS: { path: '/banner/newTos', method: Tw.API_METHOD.GET },
  GET_MASKING_METHOD: { path: '/masking-method', method: Tw.API_METHOD.GET },
  SET_MASKING_COMPLETE: { path: '/masking-complete', method: Tw.API_METHOD.POST },
  DELETE_SESSION_STORE: { path: '/session-store', method: Tw.API_METHOD.DELETE },
  GET_HOME_WELCOME: { path: '/home/welcome', method: Tw.API_METHOD.GET },
  GET_HOME_NOTICE: { path: '/home/notice', method: Tw.API_METHOD.GET },
  GET_HOME_HELP: { path: '/home/help', method: Tw.API_METHOD.GET },
  GET_TOOLTIP: { path: '/tooltip', method: Tw.API_METHOD.GET },
  GET_QUICK_MENU: { path: '/home/quick-menu', method: Tw.API_METHOD.GET },
  GET_QUICK_MENU_DEFAULT: { path: '/home/quick-menu/default', method: Tw.API_METHOD.GET },
  GET_PRODUCT_COMPARISON: { path: '/product/comparison', method: Tw.API_METHOD.GET },
  GET_PRODUCT_INFO: { path: '/product/info', method: Tw.API_METHOD.GET },
  GET_AUTH_METHOD_BLOCK: { path: '/auth-method/block', method: Tw.API_METHOD.GET }
};

Tw.SESSION_CMD = {
  BFF_04_0001: { path: '/core-membership/:version/card/homeinfo', method: Tw.API_METHOD.GET, command: 'BFF_04_0001' },
  BFF_05_0001: { path: '/:version/my-t/balances', method: Tw.API_METHOD.GET, command: 'BFF_05_0001' },
  BFF_07_0017: { path: '/core-bill/:version/bill-pay/tax-reprint', method: Tw.API_METHOD.GET, command: 'BFF_07_0017' }
};

Tw.TMAP = {
  URL: 'https://api2.sktelecom.com/tmap',
  PIN: '/img/ico/ico-tmap-pin.png',
  COMPASS: '/img/ico/ico-tmap-compass.png',
  APP_KEY: 'ecfeceac-3660-4618-bc3b-37a11f952441'
};

Tw.AJAX_CMD = {
  GET_TMAP_REGION: { path: '/geofencing/regions', method: Tw.API_METHOD.GET, url: Tw.TMAP.URL },
  GET_TMAP_AREASCODE: { path: '/poi/areascode', method: Tw.API_METHOD.GET, url: Tw.TMAP.URL },
  GET_TMAP_ADDR_GEO: { path: '/geo/fullAddrGeo', method: Tw.API_METHOD.GET, url: Tw.TMAP.URL },
  GET_TMAP_POI: { path: '/pois', method: Tw.API_METHOD.GET, url: Tw.TMAP.URL },
  OPEN_NICE_AUTH: {
    path: '',
    method: Tw.API_METHOD.POST,
    url: Tw.NICE_URL,
    contentType: 'application/x-www-form-urlencoded'
  },
  OPEN_IPIN_AUTH: {
    path: '',
    method: Tw.API_METHOD.POST,
    url: Tw.IPIN_URL,
    contentType: 'application/x-www-form-urlencoded'
  }
};

Tw.API_CODE = {
  CODE_00: '00', // success
  BFF_0003: 'BFF0003', // 로그인 필요
  BFF_0004: 'BFF0004', // 접근 권한 필요
  BFF_0006: 'BFF0006', // BFF API 차단
  BFF_0007: 'BFF0007', // MS API 차단
  BFF_0008: 'BFF0008', // 업무인증 필요
  BFF_0009: 'BFF0009', // 마스킹&업무 인증 필요
  BFF_0010: 'BFF0010', // 상품인증 필요
  BFF_0011: 'BFF0011', // 서비스 자동 차단 (Circuit open 대체 화면)
  BFF_0012: 'BFF0012', // 고객비밀번호 인증 필요
  BFF_0013: 'BFF0013', // 고객비밀번호 인증 필요
  BFF_0014: 'BFF0014', // 고객비밀번호 재설정 필요
  BFF_0015: 'BFF0015', // 비밀번호 인증 필요 (업무인증에 옵션으로 추가되는 인증)
  BFF_0020: 'BFF0020', // 법정대리인 인증필요

  CERT_FAIL: 'TWM0001',
  CERT_SELECT: 'CERT0001', // 인증수단 선택화면으로 이동
  CERT_SMS_BLOCK: 'CERT0002', // SMS 인증 불가
  CERT_SMS_ENABLE: 'CERT0003',
  CERT_CANCEL: 'CERT0004',

  CODE_99: 'RDT0099', // Circuit Open
  CODE_200: '200',
  CODE_400: '400',

  NODE_1001: '1001',  // login 필요
  NODE_1002: '1002',  // 인증 오류
  NODE_1003: '1003',  // 처리 완료
  NODE_1004: '1004',  // 세션 만료

  NOT_FAMILY: 'ZORDE4011', // 쿠폰 선물 가능한 가족그룹 아님
  RECEIVER_LIMIT: 'ZNGME0000', // 쿠폰 받는 사람 횟수 초과

  RCG0101: 'RCG0101', // Ting 요금제 차단 상태
  ZPAYE0077: 'ZPAYE0077', // 제공자가 성인이 아닌 경우 팅충전 선물을 할 수 없습니다.
  RCG0062: 'RCG0062', // 팅,쿠키즈,안심 음성 미사용 상태

  COM001: 'COM001' // 회선번호 존재 하지 않음.
};

Tw.CALLBACK_CODE = {
  SUCCESS: '00',
  FAIL: '01',
  CANCEL: '02'
};

Tw.API_SVC_PWD_ERROR = {
  ATH3000: 'ATH3000', // 변경할 회선 고객보호비밀번호 입력 필요
  BFF9000: 'BFF9000', // 변경할 회선 고객보호비밀번호 입력 필요
  ICAS3481: 'ICAS3481', // 고객보호비밀번호 입력 오류 1회
  ICAS3482: 'ICAS3482', // 고객보호비밀번호 입력 오류 2회
  ICAS3483: 'ICAS3483', // 고객보호비밀번호 입력 오류 3회
  ICAS3484: 'ICAS3484', // 고객보호비밀번호 입력 오류 4회
  ICAS3215: 'ICAS3215', // 고객보호비밀번호 입력 오류 5회 (잠김예정)
  ICAS3216: 'ICAS3216' // 고객보호비밀번호 기 잠김
};

Tw.API_LOGIN_ERROR = {
  ATH1003: 'ATH1003', // 로그인 30회 초과
  ATH3236: 'ATH3236', // 분실정지(대표회선)
  ICAS3228: 'ICAS3228', // 고객보호비밀번호(대표회선) 입력 필요
  ICAS3235: 'ICAS3235' // 휴면계정
};

Tw.API_ADD_SVC_ERROR = {
  // 부가서비스(소액결제, 콘텐츠이용)
  BIL0030: 'BIL0030', // 휴대폰 결제 이용동의 후 사용 가능한 메뉴입니다
  BIL0031: 'BIL0031', // 미성년자는 이용할 수 없습니다
  BIL0033: 'BIL0033', // 휴대폰 결제 차단 고객은 사용이 제한된 메뉴입니다
  BIL0034: 'BIL0034', // 소액결제 부가서비스 미가입자는 이용할 수 없습니다
  BIL0035: 'BIL0035' //휴대폰 결제 차단 고객은 사용이 제한된 메뉴입니다.
};
