Tw.MYT_FARE_AUTO = {
  'Y': '신청',
  'N': '미신청'
};

Tw.TING_TITLE = {
  'HA': '통화가능금액',
  'CH': '충전금액',
  'PR': '선물충전금액'
};

Tw.MYT_FARE_SUB_MAIN = {
  NO_BILL_REQUEST_EXIST: 'ZINVN8888'
};

Tw.PAYMENT_POINT_VALUE = {
  OK_CASHBAG: '10',
  T_POINT: '11'
};

Tw.LINE_NAME = {
  MOBILE: 'M',
  INTERNET_PHONE_IPTV: 'S',
  SECURITY: 'O'
};


Tw.HOME_SMART_CARD_E = {
  CHILD: 'H01',
  BILL: 'H02',
  NON_PAYMENT: 'H03',
  SUSPENSION: 'H04',
  MEMBERSHIP: 'H05',
  CONTENT: 'H06',
  MICRO_PAY: 'H07',
  COLORING: 'H08',
  DEVICE: 'H09',
  GIFT: 'H10',
  RECHARGE: 'H11',
  AUTO: 'H12',
  DIRECT: 'H13',
  ROAMING: 'H14',
  PRODUCT: 'H15',
  ADDITIONAL: 'H16'
};
