Tw.LSTORE_KEY = {
  HOME_WELCOME: 'homeWelcome',
  HOME_EMR_NOTICE: 'homeEmrNotice'
};

Tw.FIDO_TYPE = {
  FINGER: 'finger',
  FACE: 'face'
};

Tw.UPLOAD_TYPE = {
  EMAIL: 'email',
  RESERVATION: 'reservation',
  SUSPEND: 'suspend'
};

Tw.INIT_COMPLETE = 'env';

Tw.COOKIE_KEY = {
  DEVICE: 'TWM_DEVICE',
  CHANNEL: 'TWM_CHANNEL',
  TWM_LOGIN: 'TWM_LOGIN',
  TWM: 'TWM',
  SESSION: 'SESSION',
  LAYER_CHECK: 'LAYER_CHECK',
  APP_API: 'APP_API',
  XTLID: 'XTLID',
  XTLOGINID: 'XTLOGINID',
  XTUID: 'XTUID',
  XTLOGINTYPE: 'XTLOGINTYPE',
  XTSVCGR: 'XTSVCGR'
};
