// Common
Tw.DEFAULT_LIST_COUNT = 20;
Tw.MAX_FILE_SIZE = 2 * 1024 * 1024;
Tw.SESSION_EXPIRE_TIME = 60 * 60 * 1000;

// Auth
Tw.MAX_NICKNAME_LEN = 7;
Tw.BIRTH_LEN = 6;
Tw.BIRTH_Y_LEN = 4;
Tw.BIRTH_MD_LEN = 2;
Tw.DEFAULT_CERT_LEN = 6;
Tw.MOTP_CERT_LEN = 4;
Tw.MIN_MDN_LEN = 10;
Tw.MAX_MDN_LEN = 11;
Tw.SMS_CERT_TIME = 5 * 60 * 1000;

// gift
Tw.GIFT_REMAIN_RETRY = 5;
Tw.GIFT_BLOCK_USAGE = 1;