// Common
Tw.DEFAULT_LIST_COUNT = 20;
Tw.MAX_FILE_SIZE = 30 * 1024 * 1024;

// Auth
Tw.MAX_NICKNAME_LEN = 7;
Tw.BIRTH_LEN = 6;
Tw.DEFAULT_CERT_LEN = 6;
Tw.MOTP_CERT_LEN = 4;
Tw.MIN_MDN_LEN = 10;
Tw.MAX_MDN_LEN = 11;

// gift
Tw.GIFT_REMAIN_RETRY = 5;
Tw.GIFT_BLOCK_USAGE = 1;