Tw.OUTLINK = {
  TPLECARD_BENEFIT: 'http://tmembership.tworld.co.kr/web/html/lte/tple/tple_info.jsp',
  COUPLECARD_BENEFIT: 'http://tmembership.tworld.co.kr/web/html/lte/couple/couple_info.jsp',
  DATA_FACTORY: 'http://tmembership.tworld.co.kr/web/html/data/dataFactory.jsp',
  MOBILE_TWORLD: 'http://m2.tworld.co.kr/jsp/op.jsp?p=w70&f=a0001',
  GOOGLE_STORE: 'https://play.google.com/store/apps/details?id=Com.sktelecom.minit',
  ONE_STORE: 'https://www.onestore.co.kr/userpoc/game/view?pid=0000032819',
  APP_STORE: 'https://itunes.apple.com/kr/app/%EB%AA%A8%EB%B0%94%EC%9D%BCtworld/id428872117?mt=8',
  DIRECT_SUPPORT: 'http://shop.tworld.co.kr/handler/Dantong-SKT?UPDATE_YN=N&_ga=2.226795357.1794270396.1498012356-98061374.1498012356',
  DIRECT_HOME: 'http://shop.tworld.co.kr/handler/ShopTworldMain-Start',
  DIRECT_ACCESSORY: 'http://shop.tworld.co.kr/handler/AccessoryMall-MainAcc',
  DIRECT_PHONE: 'http://shop.tworld.co.kr/handler/Mobile-MobileMain?category_id=20010001',
  DIRECT_TABLET: 'http://shop.tworld.co.kr/handler/Mobile-MobileMain?category_id=20010002',
  DIRECT_NUGU: 'http://shop.tworld.co.kr/handler/AccessoryMall-StartAcc?categoryId=10010003',
  BROADBAND: 'http://www.skbroadband.com/Main.do',
  MEMBERSHIP_MOVIE_APP: 'http://www.sktmembership.co.kr:90/mobile/tm.jsp?m1=00&targetUrl=/benefit/culture/movieList.do?bannerpoc=2018_168',
  MEMBERSHIP_MOVIE_WEB: 'http://www.sktmembership.co.kr:90/mobile/tm.jsp?m1=00&targetUrl=/benefit/culture/movieList.do?bannerpoc=2018_169',
  MEMBERSHIP_CULTURE_APP: 'http://www.sktmembership.co.kr:90/mobile/tm.jsp?m1=00&targetUrl=/benefit/culture/cultureList.do?bannerpoc=2018_166',
  MEMBERSHIP_CULTURE_WEB: 'http://www.sktmembership.co.kr:90/mobile/tm.jsp?m1=00&targetUrl=/benefit/culture/cultureList.do?bannerpoc=2018_164'
};
