import TwRouter from '../../common/route/tw.router';
import MyTFareSubMain from './myt-fare.submain.controller';
import MyTFareBillGuide from './controllers/bill/myt-fare.bill.guide.controllers';
import MyTFareBillSet from './controllers/bill/myt-fare.bill.set.controller';
import MyTFareBillSetReissue from './controllers/bill/myt-fare.bill.set.reissue.controller';
import MyTFareBillSetReturnHistory from './controllers/bill/myt-fare.bill.set.return-history.controller';
import MyTFarePaymentAuto from './controllers/payment/myt-fare.payment.auto.controller';
import MyTFarePaymentAccount from './controllers/payment/myt-fare.payment.account.controller';
import MyTFarePaymentCard from './controllers/payment/myt-fare.payment.card.controller';
import MyTFarePaymentPoint from './controllers/payment/myt-fare.payment.point.controller';
import MyTFarePaymentSms from './controllers/payment/myt-fare.payment.sms.controller';
import MytFareHotbill from './controllers/bill/myt-fare.bill.hotbill.controller';
import MyTFareBillSetChange from './controllers/bill/myt-fare.bill.set.change.controller';
import MyTFareBillGuideCallGift from './controllers/bill/myt-fare.bill.guide.call-gift.controllers';
import MyTFareBillGuideRoaming from './controllers/bill/myt-fare.bill.guide.roaming.controllers';
import MyTFareBillGuideDonation from './controllers/bill/myt-fare.bill.guide.donation.controllers';
import MyTFareSubMainNonPayment from './controllers/submain/myt-fare.submain.non-paymt';
import MyTFarePaymentOption from './controllers/payment/myt-fare.payment.option.controller';
import MyTFarePaymentMicro from './controllers/payment/myt-fare.payment.micro.controller';
import MyTFarePaymentMicroAuto from './controllers/payment/myt-fare.payment.micro.auto.controller';
import MyTFarePaymentMicroAutoChange from './controllers/payment/myt-fare.payment.micro.auto.change.controller';
import MyTFareBillSetComplete from './controllers/bill/myt-fare.bill.set.complete.controller';
import MyTFarePaymentMicroAutoInfo from './controllers/payment/myt-fare.payment.micro.auto.info.controller';
import MyTFarePaymentContents from './controllers/payment/myt-fare.payment.contents.controller';
import MyTFarePaymentContentsAuto from './controllers/payment/myt-fare.payment.contents.auto.controller';
import MyTFarePaymentContentsAutoInfo from './controllers/payment/myt-fare.payment.contents.auto.info.controller';
import MyTFarePaymentContentsAutoChange from './controllers/payment/myt-fare.payment.contents.auto.change.controller';
import MyTFareHistory from './controllers/history/myt-fare.history.controller';
import MyTFarePaymentHistory from './controllers/history/myt-fare.payment.history.controller';
import MyTFareBillHistory from './controllers/history/myt-fare.bill-history.controller';
import MyTFareOverpayRefund from './controllers/history/myt-fare.overpay-refund.controller';

import MyTFareHistory from './controllers/history/myt-fare.history.controller';
import MyTFarePaymentHistory from './controllers/history/myt-fare.payment.history.controller';
import MyTFareBillHistory from './controllers/history/myt-fare.bill-history.controller';
import MyTFareOverpayRefund from './controllers/history/myt-fare.overpay-refund.controller';

class MytFareRouter extends TwRouter {
  constructor() {
    super();
    this.controllers.push({ url: '/', controller: new MyTFareSubMain() });
    this.controllers.push({ url: '/nonpayment', controller: new MyTFareSubMainNonPayment() });
    this.controllers.push({ url: '/bill/guide', controller: new MyTFareBillGuide() });
    this.controllers.push({ url: '/bill/guide/call-gift', controller: new MyTFareBillGuideCallGift() });
    this.controllers.push({ url: '/bill/guide/roaming', controller: new MyTFareBillGuideRoaming() });
    this.controllers.push({ url: '/bill/guide/donation', controller: new MyTFareBillGuideDonation() });
    this.controllers.push({ url: '/bill/set', controller: new MyTFareBillSet() });
    this.controllers.push({ url: '/bill/set/reissue', controller: new MyTFareBillSetReissue() });
    this.controllers.push({ url: '/payment/option', controller: new MyTFarePaymentOption() });
    this.controllers.push({ url: '/payment/auto', controller: new MyTFarePaymentAuto() });
    this.controllers.push({ url: '/payment/account', controller: new MyTFarePaymentAccount() });
    this.controllers.push({ url: '/payment/card', controller: new MyTFarePaymentCard() });
    this.controllers.push({ url: '/payment/point', controller: new MyTFarePaymentPoint() });
    this.controllers.push({ url: '/payment/sms', controller: new MyTFarePaymentSms() });
    this.controllers.push({ url: '/payment/micro', controller: new MyTFarePaymentMicro() });
    this.controllers.push({ url: '/payment/micro/auto', controller: new MyTFarePaymentMicroAuto() });
    this.controllers.push({ url: '/payment/micro/auto/info', controller: new MyTFarePaymentMicroAutoInfo() });
    this.controllers.push({ url: '/payment/micro/auto/change', controller: new MyTFarePaymentMicroAutoChange() });
    this.controllers.push({ url: '/payment/contents', controller: new MyTFarePaymentContents() });
    this.controllers.push({ url: '/payment/contents/auto', controller: new MyTFarePaymentContentsAuto() });
    this.controllers.push({ url: '/payment/contents/auto/info', controller: new MyTFarePaymentContentsAutoInfo() });
    this.controllers.push({ url: '/payment/contents/auto/change', controller: new MyTFarePaymentContentsAutoChange() });
    this.controllers.push({ url: '/bill/set/return-history', controller: new MyTFareBillSetReturnHistory() });
    this.controllers.push({ url: '/bill/set/change', controller: new MyTFareBillSetChange() });
    this.controllers.push({ url: '/bill/set/complete', controller: new MyTFareBillSetComplete() });
    this.controllers.push({ url: '/bill/hotbill', controller: new MytFareHotbill() });
    this.controllers.push({ url: '/history/micro', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/micro/monthly', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/micro/block', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/micro/detail', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/contents', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/contents/monthly', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/contents/detail', controller: new MyTFareHistory() });
    this.controllers.push({ url: '/history/payment', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/payment/all', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/payment/direct', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/payment/auto', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/payment/auto-all', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/payment/micro-prepay', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/payment/content-prepay', controller: new MyTFarePaymentHistory() });
    this.controllers.push({ url: '/history/bill/tax', controller: new MyTFareBillHistory() });
    this.controllers.push({ url: '/history/bill/cash', controller: new MyTFareBillHistory() });
    this.controllers.push({ url: '/history/overpay-refund', controller: new MyTFareOverpayRefund() });
  }
}

export default MytFareRouter;
